import {
  ADMIN_COPY,
  AUTH_COPY,
  AUTHOR_COPY,
  CHARACTER_COPY,
  CHAT_COPY,
  CONFIRM_COPY,
  CONNECT_COPY,
  CONNECT_MESSAGES,
  CONNECTION_COPY,
  DASHBOARD_COPY,
  ENHANCE_COPY,
  GALLERY_COPY,
  HOME_COPY,
  MOMENT_COPY,
  MOOD_COPY,
  OUTFIT_COPY,
  PHOTO_COPY,
  STATUS_COPY,
  THEME_COPY,
} from "../copy";
import { CHAT, CHAT_MS, PHOTO, RECONNECT_DELAYS_MS, SOCKET } from "../defaults";
import { AFFINITY_HUD, MIND_COPY } from "../hud";
import { CALL, CALL_COPY, CALL_MS, IMPORT_COPY, SPEECH } from "../live-voice";
import { CHRONICLE_PAGING } from "../memory";
import {
  EASING,
  EASING_BEZIER,
  FIELD_PADDING,
  GALLERY,
  MEDIA_PREVIEW,
  PORTRAIT_POLL_MS,
  PRESS_SCALE,
  SEGMENTED,
  UI_MS,
} from "../motion";
import { VOICE_COPY } from "../voice";
import { REASONS } from "./reasons";
import type { ConfigGroup } from "./types";

const COPY_GROUPS: ConfigGroup[] = [
  { name: "STATUS_COPY", value: STATUS_COPY },
  { name: "CONNECTION_COPY", value: CONNECTION_COPY },
  { name: "CONFIRM_COPY", value: CONFIRM_COPY },
  { name: "MOMENT_COPY", value: MOMENT_COPY },
  { name: "OUTFIT_COPY", value: OUTFIT_COPY },
  { name: "PHOTO_COPY", value: PHOTO_COPY },
  { name: "CONNECT_COPY", value: CONNECT_COPY },
  { name: "CONNECT_MESSAGES", value: CONNECT_MESSAGES },
  { name: "HOME_COPY", value: HOME_COPY },
  { name: "THEME_COPY", value: THEME_COPY },
  { name: "ENHANCE_COPY", value: ENHANCE_COPY },
  { name: "AUTHOR_COPY", value: AUTHOR_COPY },
  { name: "GALLERY_COPY", value: GALLERY_COPY },
  { name: "CHARACTER_COPY", value: CHARACTER_COPY },
  { name: "MOOD_COPY", value: MOOD_COPY },
  { name: "CHAT_COPY", value: CHAT_COPY },
  { name: "ADMIN_COPY", value: ADMIN_COPY },
  { name: "AUTH_COPY", value: AUTH_COPY },
  { name: "DASHBOARD_COPY", value: DASHBOARD_COPY },
].map((entry) => ({
  ...entry,
  source: "copy.ts",
  bucket: "structural" as const,
  reason: REASONS.copy,
}));

export const INTERFACE_GROUPS: ConfigGroup[] = [
  ...COPY_GROUPS,
  {
    name: "MIND_COPY",
    source: "hud.ts",
    value: MIND_COPY,
    bucket: "structural",
    reason: REASONS.copy,
  },
  {
    name: "VOICE_COPY",
    source: "voice.ts",
    value: VOICE_COPY,
    bucket: "structural",
    reason: REASONS.copy,
  },
  {
    name: "CALL_COPY",
    source: "live-voice.ts",
    value: CALL_COPY,
    bucket: "structural",
    reason: REASONS.copy,
  },
  {
    name: "IMPORT_COPY",
    source: "live-voice.ts",
    value: IMPORT_COPY,
    bucket: "structural",
    reason: REASONS.copy,
  },
  {
    name: "AFFINITY_HUD",
    source: "hud.ts",
    value: AFFINITY_HUD,
    bucket: "boot-bound",
    reason: REASONS.canvasBundled,
  },
  {
    name: "CHAT",
    source: "defaults.ts",
    value: CHAT,
    bucket: "boot-bound",
    reason: REASONS.canvasBundled,
  },
  {
    name: "CHAT_MS",
    source: "defaults.ts",
    value: CHAT_MS,
    bucket: "boot-bound",
    reason: REASONS.canvasBundled,
  },
  {
    name: "PHOTO",
    source: "defaults.ts",
    value: PHOTO,
    bucket: "boot-bound",
    reason: REASONS.canvasBundled,
  },
  {
    name: "SOCKET",
    source: "defaults.ts",
    value: SOCKET,
    bucket: "boot-bound",
    reason: REASONS.canvasBundled,
  },
  {
    name: "RECONNECT_DELAYS_MS",
    source: "defaults.ts",
    value: RECONNECT_DELAYS_MS,
    bucket: "boot-bound",
    reason: REASONS.canvasBundled,
  },
  {
    name: "CALL",
    source: "live-voice.ts",
    value: CALL,
    bucket: "boot-bound",
    reason: REASONS.canvasBundled,
  },
  {
    name: "CALL_MS",
    source: "live-voice.ts",
    value: CALL_MS,
    bucket: "boot-bound",
    reason: REASONS.canvasBundled,
  },
  {
    name: "SPEECH",
    source: "live-voice.ts",
    value: SPEECH,
    bucket: "boot-bound",
    reason: REASONS.canvasBundled,
  },
  {
    name: "UI_MS",
    source: "motion.ts",
    value: UI_MS,
    bucket: "boot-bound",
    reason: REASONS.canvasBundled,
  },
  {
    name: "EASING",
    source: "motion.ts",
    value: EASING,
    bucket: "boot-bound",
    reason: REASONS.canvasBundled,
  },
  {
    name: "EASING_BEZIER",
    source: "motion.ts",
    value: EASING_BEZIER,
    bucket: "boot-bound",
    reason: REASONS.canvasBundled,
  },
  {
    name: "FIELD_PADDING",
    source: "motion.ts",
    value: FIELD_PADDING,
    bucket: "boot-bound",
    reason: REASONS.canvasBundled,
  },
  {
    name: "GALLERY",
    source: "motion.ts",
    value: GALLERY,
    bucket: "boot-bound",
    reason: REASONS.canvasBundled,
  },
  {
    name: "SEGMENTED",
    source: "motion.ts",
    value: SEGMENTED,
    bucket: "boot-bound",
    reason: REASONS.canvasBundled,
  },
  {
    name: "MEDIA_PREVIEW",
    source: "motion.ts",
    value: MEDIA_PREVIEW,
    bucket: "boot-bound",
    reason: REASONS.canvasBundled,
  },
  {
    name: "PORTRAIT_POLL_MS",
    source: "motion.ts",
    value: PORTRAIT_POLL_MS,
    bucket: "boot-bound",
    reason: REASONS.canvasBundled,
  },
  {
    name: "PRESS_SCALE",
    source: "motion.ts",
    value: PRESS_SCALE,
    bucket: "boot-bound",
    reason: REASONS.canvasBundled,
  },
  {
    name: "CHRONICLE_PAGING",
    source: "memory.ts",
    value: CHRONICLE_PAGING,
    bucket: "boot-bound",
    reason: REASONS.canvasBundled,
  },
];
