import {
  AFFINITY,
  AUDIT,
  AUTH,
  CACHE,
  CHAT_TURN,
  DATA_FILES,
  DEFAULT_PRONOUNS,
  ENHANCE,
  IMAGE_ENCODE,
  MEDIA_KINDS,
  MEDIA_TYPES,
  MEMORY,
  OUTPUT_TAGS,
  PERSONA_GUARD,
  PRONOUN_SETS,
  REPLY_VARIANTS,
  SEARCH,
  SERVER_DEFAULTS,
  STAGE_DIRECTIONS,
  STORAGE,
  STORAGE_BROWSER,
  STORAGE_SWEEP,
  SUGGESTIONS,
  TIMEOUTS_MS,
  TRANSCRIPT,
  TTS,
  USER_ROLES,
} from "../defaults";
import { REASONS } from "./reasons";
import type { ConfigGroup } from "./types";

const SOURCE = "defaults.ts";

export const RUNTIME_GROUPS: ConfigGroup[] = [
  {
    name: "SUGGESTIONS",
    source: SOURCE,
    value: SUGGESTIONS,
    bucket: "editable",
    reason: REASONS.requestRead,
  },
  {
    name: "STAGE_DIRECTIONS",
    source: SOURCE,
    value: STAGE_DIRECTIONS,
    bucket: "editable",
    reason: REASONS.requestRead,
  },
  {
    name: "ENHANCE",
    source: SOURCE,
    value: ENHANCE,
    bucket: "editable",
    reason: REASONS.requestRead,
  },
  {
    name: "TRANSCRIPT",
    source: SOURCE,
    value: TRANSCRIPT,
    bucket: "editable",
    reason: REASONS.requestRead,
  },
  {
    name: "CHAT_TURN",
    source: SOURCE,
    value: CHAT_TURN,
    bucket: "editable",
    reason: REASONS.requestRead,
  },
  {
    name: "PERSONA_GUARD",
    source: SOURCE,
    value: PERSONA_GUARD,
    bucket: "editable",
    reason: REASONS.requestRead,
  },
  {
    name: "REPLY_VARIANTS",
    source: SOURCE,
    value: REPLY_VARIANTS,
    bucket: "editable",
    reason: REASONS.requestRead,
  },
  {
    name: "TIMEOUTS_MS",
    source: SOURCE,
    value: TIMEOUTS_MS,
    bucket: "editable",
    reason: "The conductor reads this per request. The canvas keeps its own bundled copy.",
  },
  {
    name: "AFFINITY",
    source: SOURCE,
    value: AFFINITY,
    bucket: "editable",
    reason: REASONS.requestRead,
    leaves: {
      min: { bucket: "boot-bound", reason: REASONS.affinityScale },
      max: { bucket: "boot-bound", reason: REASONS.affinityScale },
    },
  },
  {
    name: "MEMORY",
    source: SOURCE,
    value: MEMORY,
    bucket: "service-bound",
    boundTo: "LanceDB",
    reason: REASONS.lanceBound,
    leaves: {
      searchLimit: { bucket: "editable", reason: REASONS.requestRead },
    },
  },
  {
    name: "SEARCH",
    source: SOURCE,
    value: SEARCH,
    bucket: "editable",
    reason: REASONS.requestRead,
  },
  {
    name: "MEDIA_TYPES",
    source: SOURCE,
    value: MEDIA_TYPES,
    bucket: "structural",
    reason: "File extensions both apps agree on to tell a picture from a recording.",
  },
  {
    name: "MEDIA_KINDS",
    source: SOURCE,
    value: MEDIA_KINDS,
    bucket: "structural",
    reason: REASONS.typeLevel,
  },
  {
    name: "STORAGE_BROWSER",
    source: SOURCE,
    value: STORAGE_BROWSER,
    bucket: "editable",
    reason: REASONS.requestRead,
  },
  {
    name: "STORAGE_SWEEP",
    source: SOURCE,
    value: STORAGE_SWEEP,
    bucket: "editable",
    reason: "The sweep re-reads this each pass, so a change lands on the next one.",
    leaves: {
      sources: { bucket: "structural", reason: REASONS.dbShape },
    },
  },
  {
    name: "IMAGE_ENCODE",
    source: SOURCE,
    value: IMAGE_ENCODE,
    bucket: "editable",
    reason: REASONS.requestRead,
    leaves: {
      format: { bucket: "structural", reason: REASONS.storedShape },
      extension: { bucket: "structural", reason: REASONS.storedShape },
    },
  },
  {
    name: "CACHE",
    source: SOURCE,
    value: CACHE,
    bucket: "editable",
    reason: REASONS.requestRead,
    leaves: {
      defaultUrl: { bucket: "deployment", boundTo: "REDIS_URL", reason: REASONS.envVar },
      defaultPort: { bucket: "deployment", boundTo: "REDIS_URL", reason: REASONS.envVar },
      promptsKey: { bucket: "structural", reason: REASONS.redisKey },
    },
  },
  {
    name: "TTS",
    source: SOURCE,
    value: TTS,
    bucket: "editable",
    reason: REASONS.requestRead,
    leaves: {
      voice: { bucket: "service-bound", boundTo: "Kokoro", reason: REASONS.kokoroBound },
      format: { bucket: "service-bound", boundTo: "Kokoro", reason: REASONS.kokoroBound },
    },
  },
  {
    name: "AUTH",
    source: SOURCE,
    value: AUTH,
    bucket: "boot-bound",
    reason: REASONS.authBoot,
    leaves: {
      ownerRole: { bucket: "structural", reason: REASONS.typeLevel },
      memberRole: { bucket: "structural", reason: REASONS.typeLevel },
      defaultRole: { bucket: "structural", reason: REASONS.typeLevel },
      roleField: { bucket: "structural", reason: REASONS.dbShape },
    },
  },
  {
    name: "AUDIT",
    source: SOURCE,
    value: AUDIT,
    bucket: "editable",
    reason: "The audit log reads this each time it writes or is paged.",
  },
  {
    name: "USER_ROLES",
    source: SOURCE,
    value: USER_ROLES,
    bucket: "structural",
    reason: REASONS.typeLevel,
  },
  {
    name: "STORAGE",
    source: SOURCE,
    value: STORAGE,
    bucket: "structural",
    reason: REASONS.storedShape,
    leaves: {
      defaultRegion: { bucket: "deployment", boundTo: "S3_REGION", reason: REASONS.envVar },
      requiredEnv: { bucket: "deployment", reason: REASONS.envVar },
    },
  },
  {
    name: "SERVER_DEFAULTS",
    source: SOURCE,
    value: SERVER_DEFAULTS,
    bucket: "deployment",
    boundTo: "PORT, HOST",
    reason: REASONS.envVar,
  },
  {
    name: "DATA_FILES",
    source: SOURCE,
    value: DATA_FILES,
    bucket: "deployment",
    boundTo: "EIDOLON_DATA_DIR",
    reason: REASONS.envVar,
  },
  {
    name: "OUTPUT_TAGS",
    source: SOURCE,
    value: OUTPUT_TAGS,
    bucket: "structural",
    reason: REASONS.wireFormat,
  },
  {
    name: "PRONOUN_SETS",
    source: SOURCE,
    value: PRONOUN_SETS,
    bucket: "structural",
    reason: REASONS.typeLevel,
  },
  {
    name: "DEFAULT_PRONOUNS",
    source: SOURCE,
    value: DEFAULT_PRONOUNS,
    bucket: "structural",
    reason: REASONS.typeLevel,
  },
];
