export const STATUS_COPY = {
  thinking: { label: "Typing", line: "Typing…" },
  searching: { label: "Looking it up", line: "Checking what's happening out there" },
  painting: { label: "Taking a photo", line: "Capturing the moment" },
  speaking: { label: "Speaking", line: "Saying it out loud" },
  idle: { label: "Here", line: "" },
} as const;

export const CONNECTION_COPY = {
  connected: "Active now",
  connecting: "Reaching out…",
  reconnecting: "Reaching out again…",
  disconnected: "Out of reach",
} as const;

export const PHOTO_COPY = {
  framing: "Finding the light",
  taking: "Capturing the moment",
  noCamera: "No camera on this side",
  didNotCome: "That photo did not come out",
} as const;

export const PAIRING_COPY = {
  title: "Connect to your Eidolon",
  subtitle: "Scan the code showing on your computer",
  connecting: "Connecting…",
  cameraNeeded: "Let the camera see the code on your computer.",
  allowCamera: "Allow camera",
  manual: "Type it in instead",
  addressLabel: "Address",
  passphraseLabel: "Passphrase",
  passphraseHint: "The word shown on your computer",
  connect: "Connect",
  missingFields: "Fill in both the address and the passphrase.",
  notOurCode: "That is not an Eidolon code. Scan the one showing on your computer.",
  incompleteCode: "That code is incomplete. Show the full one on your computer and scan again.",
  refused: "That passphrase was not accepted. Check it matches the one on your computer.",
  serverError: "Your Eidolon answered, but something went wrong at its end. Check it is running.",
  unreachable:
    "Could not reach that address. Check it matches your computer and that you are both on the same network.",
} as const;

export const PAIRING_MESSAGES: readonly string[] = [
  PAIRING_COPY.missingFields,
  PAIRING_COPY.notOurCode,
  PAIRING_COPY.incompleteCode,
  PAIRING_COPY.refused,
  PAIRING_COPY.serverError,
  PAIRING_COPY.unreachable,
];

export const HOME_COPY = {
  connectedTo: "Connected to",
  disconnect: "Disconnect",
  whosHere: "Who's here",
  ready: "Ready when you are",
  sayHello: "Say hello",
  lookTitle: "Look & feel",
  lookBlurb: "Set the colours, type and corners — for everyone, or for one character.",
  typeTitle: "Type & fonts",
  typeBlurb: "Browse fonts and see them in place before you keep them.",
  open: "Open",
} as const;

export const THEME_COPY = {
  appliesTo: "Applies to",
  everyone: "Everyone",
  ownLook: "Custom look",
  sameAsEveryone: "Same as everyone",
  corners: "Corners",
  glass: "Glass",
  glassOff: "Off",
  background: "Background",
  cards: "Cards",
  cardEdges: "Card edges",
  accent: "Accent",
  textOnAccent: "Text on accent",
  quietButtons: "Quiet buttons",
  textOnQuietButtons: "Text on quiet buttons",
  success: "Success",
  caution: "Caution",
  danger: "Danger",
  type: "Type",
  dialogue: "Dialogue",
  interface: "Interface",
  whatIsSet: "What's set right now",
  startOver: "Start over",
} as const;

export type StatusKey = keyof typeof STATUS_COPY;
export type ConnectionKey = keyof typeof CONNECTION_COPY;

export const ENHANCE_COPY = {
  action: "Rework this",
  working: "Reworking your message",
  revert: "Undo the rework",
  revertCount: (steps: number) => (steps === 1 ? "Undo the rework" : `Undo rework (${steps})`),
  failed: "Could not rework that. Your message is untouched.",
} as const;

export const AUTHOR_COPY = {
  suggest: "Write this for me",
  enhance: "Improve what I wrote",
  revert: "Put back what was there",
  working: "Writing",
  failed: "The model could not write that one. Try again.",
  portraitTitle: "Portrait",
  portraitBlurb:
    "Rendered from the personality, plus anything you add here. Takes a minute or two on the GPU.",
  portraitExtraLabel: "Anything else to include",
  portraitExtraHint: "Clothing, setting, mood. Leave it blank to go on the description alone.",
  portraitGenerate: "Generate portrait",
  portraitRegenerate: "Generate a new portrait",
  portraitQueued: "Queued. The new face will appear here when the GPU is done.",
  portraitFailed: "Could not start the render.",
  portraitWaiting: "Rendering",
} as const;

export const GALLERY_COPY = {
  title: "Everything they have shown you",
  empty: "No pictures yet. Ask for one and it will land here.",
  emptyAction: "Open the chat",
  counter: "%d of %t",
  closeLabel: "Close the picture",
  saveLabel: "Save to device",
  imageLabel: "A picture from your history together",
  saved: "Saved to your photos.",
  saveFailed: "Could not save that one.",
  photos: "Photos",
  portrait: "Portrait",
  backdrops: "Backdrops",
  all: "All",
  openChat: "Open chat",
  settings: "Settings",
  countOne: "1 picture",
  countMany: "%d pictures",
  messagesOne: "1 message",
  messagesMany: "%d messages",
  loading: "Looking through the pictures",
  loadingRoster: "Finding everyone",
  loadingChat: "Opening the conversation",
  loadFailed: "Could not reach the conversation.",
  retry: "Try again",
  findInChat: "Find it in the chat",
  useAsAvatar: "Profile picture",
  useAsFace: "Use as the face",
  useAsBackground: "Chat background",
  deleteLabel: "Delete",
  deleted: "Deleted.",
  deleteFailed: "Could not remove that one.",
  setAsAvatar: "Set as the profile picture.",
  setAsFace: "They will look like this in new photos.",
  setAsBackground: "Set as the chat background.",
} as const;

export const CHARACTER_COPY = {
  rosterTitle: "Who's here",
  newCharacter: "New character",
  createTitle: "New character",
  editTitle: "Edit character",
  presetsTitle: "Start from a preset",
  presetsBlurb: "A written character to begin with. Everything stays editable afterwards.",
  fromBlank: "Write one from nothing",
  save: "Save",
  saving: "Saving",
  create: "Create",
  creating: "Creating",
  cancel: "Cancel",
  deleteLabel: "Delete character",
  portrait: "Generate a portrait",
  portraitQueued: "Queued. The face will appear on the roster shortly.",
  failed: "Could not reach the conductor.",
  emptyRoster: "Nobody here yet. Start from a preset, or write one from nothing.",
  nameLabel: "Name",
  nameHint: "What you call them.",
  taglineLabel: "Tagline",
  taglineHint: "One line about who they are. Shown on the roster.",
  personalityLabel: "Personality",
  personalityHint: "How they think and behave, in prose.",
  scenarioLabel: "Scenario",
  scenarioHint: "Where the two of you are and how you know each other.",
  rulesLabel: "Rules",
  rulesHint:
    "Things they always or never do. Kept apart from personality so you can edit either alone.",
  examplesLabel: "Example dialogue",
  examplesHint: "A few exchanges showing how they talk. The strongest lever on their voice.",
  greetingLabel: "Greeting",
  greetingHint: "The first thing they say when a chat starts empty.",
  editBlurb: "Everything here shapes how they write.",
  forkedNote: "Your copy. The original is untouched.",
  saved: "Saved.",
  savedAsCopy: "Saved as your own copy.",
  themeLabel: "Adjust their theme",
  publishLabel: "Publish",
  publishHint: "Makes them visible to everyone on this conductor. Only their author can publish.",
  publishRefused: "Only their author can publish them.",
  systemLabel: "System prompt",
  systemHint: "Extra instructions, if you want them. Optional.",
  backLabel: "Close settings",
  sectionIdentity: "Identity",
  sectionMind: "Mind",
  sectionVoice: "Voice",
  pronounsLabel: "Pronouns",
  pronounsHint: "How the character is referred to. The model is told, and the app follows.",
  sectionSharing: "Sharing",
  identityBlurb: "What they are called, and the first thing they say.",
  mindBlurb: "How they think, where you are, and what they will never do.",
  voiceBlurb: "How they sound when they send a voice note.",
  sharingBlurb: "Who else on this conductor can meet them.",
  darkLabel: "Dark mode",
  lightLabel: "Light mode",
  unsaved: "Unsaved changes",
  unsavedOne: "1 unsaved change",
  unsavedMany: "%d unsaved changes",
  discard: "Discard",
  ownerYou: "Yours",
  ownerTheirs: "Written by somebody else",
  theirsEditable:
    "Change anything you like. Saving keeps a private copy for you and leaves theirs as it is.",
  publishHintTheirs: "You can publish your own copy of them, once you have saved one.",
  ownerUnclaimed: "Unclaimed",
  forkWarning: "Your copy starts private. Publish it here when you want others to meet them.",
} as const;

export const MOOD_COPY = {
  title: "{{Their}} mood",
  hint: "Sets how {{they}} feel{{s}} going into the next reply. {{They}} may drift from it on {{their}} own.",
  close: "Close mood picker",
  holdLabel: "Hold this mood",
  holdHint:
    "Keeps {{them}} here until you turn this off. Otherwise it colours the next reply only.",
  clear: "Clear the mood",
  clearHeld: (mood: string) => `Stop holding "${mood}"`,
  clearOnce: (mood: string) => `Clear "${mood}" from the next reply`,
} as const;

export const CHAT_COPY = {
  nothingToRegenerate: "There is no reply to write again yet.",
  regenerate: "Write it again",
  anotherReply: "Say something else",
  pickReplacement: "Choose one to replace it",
  rerollOptions: "Reroll",
  dismissOptions: "Keep what she said",
  noSuggestions: "Nothing came back. Try the reroll.",
  loadingName: "Loading the name",
  speakMessage: "Read it aloud",
  nothingToSpeak: "There are no words in this one to read.",
  voiceUnconfigured: "No voice service is configured, so nothing can be read aloud.",
  voiceFailed: "The voice service did not answer. Try again.",
  respeakMessage: "Read it aloud again",
  holdToEditOption: "Tap to use it. Hold to change it first.",
  editMessage: "Edit this message",
  saveMessage: "Save",
  messageActions: "Message actions",
} as const;

export const AUTH_COPY = {
  signInRequired: "Sign in to reach this.",
  ownerOnly: "This needs the owner account.",
  noSuchAccount: "No such account.",
  lastOwner: "The last owner cannot be demoted or removed.",
  notYourself: "You cannot remove the account you are signed in as.",
  unknownRole: "Unknown role.",
  signUpTitle: "Make an account",
  signInTitle: "Sign in",
  emailLabel: "Email",
  passwordLabel: "Password",
  nameLabel: "Name",
  addressLabel: "Conductor address",
  signUpAction: "Create it",
  signInAction: "Sign in",
  signOutAction: "Sign out",
  switchToSignUp: "No account yet? Make one.",
  switchToSignIn: "Already have one? Sign in.",
  working: "One moment…",
  missingFields: "Fill in every field first.",
  failed: "That did not work. Check the address and try again.",
  firstAccountNote: "The first account on a conductor becomes its owner.",
} as const;

export const ADMIN_COPY = {
  title: "Admin controls",
  blurb: "Levers for working on a chat rather than living in one.",
  tile: "Admin",
  editAnyLabel: "Edit any message",
  editAnyHint:
    "Off, only her newest reply can be rewritten. Changing an older one leaves everything she said after it answering something that is no longer there.",
  speakAnyLabel: "Read any message aloud",
  speakAnyHint: "Shows the speaker on every one of her replies, not just the newest.",
} as const;
