export const STATUS_COPY = {
  thinking: { label: "Typing", line: "Typing…" },
  searching: { label: "Looking it up", line: "Checking what's happening out there" },
  painting: { label: "Taking a photo", line: "Capturing the moment" },
  speaking: { label: "Speaking", line: "Saying it out loud" },
  idle: { label: "Here", line: "" },
} as const;

export const CONNECTION_COPY = {
  connected: "Active now",
  connecting: "Reaching out…",
  reconnecting: "Reaching out again…",
  disconnected: "Out of reach",
} as const;

export const MOMENT_COPY = {
  title: "Where are you?",
  blurb:
    "Paint the place behind the conversation. It is rendered on the GPU and takes a minute or two.",
  placeholder: "the bar at closing time, rain on the windows",
  send: "Take us there",
  working: "Painting it…",
  queued: "It is being painted. It will appear behind the conversation.",
  needPlace: "Say where first.",
  arrived: "You are now at",
  keptYourBackground: "kept your own background",
  captionLead: "The scene shifts",
} as const;

export const OUTFIT_COPY = {
  title: "What are they wearing?",
  blurb: "Keep the same clothes across photos. Leave it empty and every photo picks its own.",
  placeholder: "green linen shirt, sleeves rolled",
  save: "Keep it",
  clear: "Let it vary",
  wearingNow: "Wearing",
  varies: "Varies with each photo",
} as const;

export const PHOTO_COPY = {
  framing: "Finding the light",
  taking: "Capturing the moment",
  noCamera: "No camera on this side",
  didNotCome: "That photo did not come out",
} as const;

export const CONNECT_COPY = {
  title: "Connect to your Eidolon",
  subtitle: "Point the app at your conductor, then sign in",
  connecting: "Connecting…",
  addressLabel: "Address",
  addressHint: "The computer running your conductor",
  reachable: "Your Eidolon answered.",
  changeAddress: "Change",
  hideAddress: "Done",
  checking: "Looking for it…",
  connect: "Connect",
  missingFields: "Fill in the address before you sign in.",
  refused: "That email and password were not accepted.",
  sessionExpired: "Your session ended. Sign in again.",
  serverError: "Your Eidolon answered, but something went wrong at its end. Check it is running.",
  unreachable:
    "Could not reach that address. Check it matches your computer and that you are both on the same network.",
} as const;

export const CONNECT_MESSAGES: readonly string[] = [
  CONNECT_COPY.missingFields,
  CONNECT_COPY.refused,
  CONNECT_COPY.sessionExpired,
  CONNECT_COPY.serverError,
  CONNECT_COPY.unreachable,
];

export const HOME_COPY = {
  connectedTo: "Connected to",
  disconnect: "Disconnect",
  accountLabel: "Your account",
  signedOutAccount: "Not signed in",
  servedFrom: "Served from",
  whosHere: "Who's here",
  rosterFailed: "The roster could not be read. Pull down to try again.",
  rosterRetry: "Try again",
  ready: "Ready when you are",
  sayHello: "Say hello",
  lookTitle: "Look & feel",
  lookBlurb: "Set the colours, type and corners — for everyone, or for one character.",
  open: "Open",
} as const;

export const THEME_COPY = {
  appliesTo: "Applies to",
  everyone: "All characters",
  onlyThem: "only",
  status: "Status",
  ownLook: "Custom look",
  sameAsEveryone: "Same as everyone",
  corners: "Corners",
  glass: "Glass",
  glassOff: "Off",
  background: "Background",
  cards: "Cards",
  cardEdges: "Card edges",
  accent: "Accent",
  textOnAccent: "Text on accent",
  quietButtons: "Quiet buttons",
  textOnQuietButtons: "Text on quiet buttons",
  success: "Success",
  caution: "Caution",
  danger: "Danger",
  type: "Type",
  dialogue: "Dialogue",
  interface: "Interface",
  whatIsSet: "What's set right now",
  startOver: "Start over",
} as const;

export type StatusKey = keyof typeof STATUS_COPY;
export type ConnectionKey = keyof typeof CONNECTION_COPY;

export const ENHANCE_COPY = {
  action: "Rework this",
  working: "Reworking your message",
  revert: "Undo the rework",
  revertCount: (steps: number) => (steps === 1 ? "Undo the rework" : `Undo rework (${steps})`),
  failed: "Could not rework that. Your message is untouched.",
} as const;

export const AUTHOR_COPY = {
  suggest: "Write this for me",
  enhance: "Improve what I wrote",
  revert: "Put back what was there",
  working: "Writing",
  failed: "The model could not write that one. Try again.",
  portraitTitle: "Portrait",
  portraitBlurb:
    "Rendered from the personality, plus anything you add here. Takes a minute or two on the GPU.",
  portraitExtraLabel: "Anything else to include",
  portraitExtraHint: "Clothing, setting, mood. Leave it blank to go on the description alone.",
  portraitGenerate: "Generate portrait",
  portraitRegenerate: "Generate a new portrait",
  portraitQueued: "Queued. The new face will appear here when the GPU is done.",
  portraitFailed: "Could not start the render.",
  portraitWaiting: "Rendering",
} as const;

export const GALLERY_COPY = {
  title: "Everything they have shown you",
  empty: "No pictures yet. Ask for one and it will land here.",
  emptyAction: "Open the chat",
  counter: "%d of %t",
  closeLabel: "Close the picture",
  saveLabel: "Save to device",
  imageLabel: "A picture from your history together",
  saved: "Saved to your photos.",
  saveFailed: "Could not save that one.",
  photos: "Photos",
  portrait: "Portrait",
  backdrops: "Backdrops",
  all: "All",
  openChat: "Open chat",
  settings: "Settings",
  countOne: "1 picture",
  countMany: "%d pictures",
  messagesOne: "1 message",
  messagesMany: "%d messages",
  loading: "Looking through the pictures",
  loadingRoster: "Finding everyone",
  loadingChat: "Opening the conversation",
  loadFailed: "Could not reach the conversation.",
  retry: "Try again",
  findInChat: "Find it in the chat",
  useAsAvatar: "Profile picture",
  useAsFace: "Use as the face",
  useAsBackground: "Chat background",
  deleteLabel: "Delete",
  deleted: "Deleted.",
  deleteFailed: "Could not remove that one.",
  setAsAvatar: "Set as the profile picture.",
  setAsFace: "They will look like this in new photos.",
  setAsBackground: "Set as the chat background.",
} as const;

export const CHARACTER_COPY = {
  rosterTitle: "Who's here",
  newCharacter: "New character",
  createTitle: "New character",
  editTitle: "Edit character",
  presetsTitle: "Start from a preset",
  presetsBlurb: "A written character to begin with. Everything stays editable afterwards.",
  fromBlank: "Write one from nothing",
  save: "Save",
  saving: "Saving",
  create: "Create",
  creating: "Creating",
  cancel: "Cancel",
  deleteLabel: "Delete character",
  portrait: "Generate a portrait",
  portraitQueued: "Queued. The face will appear on the roster shortly.",
  failed: "Could not reach the conductor.",
  emptyRoster: "Nobody here yet. Start from a preset, or write one from nothing.",
  nameLabel: "Name",
  nameHint: "What you call them.",
  taglineLabel: "Tagline",
  taglineHint: "One line about who they are. Shown on the roster.",
  personalityLabel: "Personality",
  personalityHint: "How they think and behave, in prose.",
  scenarioLabel: "Scenario",
  scenarioHint: "Where the two of you are and how you know each other.",
  rulesLabel: "Rules",
  rulesHint:
    "Things they always or never do. Kept apart from personality so you can edit either alone.",
  examplesLabel: "Example dialogue",
  examplesHint: "A few exchanges showing how they talk. The strongest lever on their voice.",
  greetingLabel: "Greeting",
  greetingHint: "The first thing they say when a chat starts empty.",
  editBlurb: "Everything here shapes how they write.",
  forkedNote: "Your copy. The original is untouched.",
  saved: "Saved.",
  savedAsCopy: "Saved as your own copy.",
  themeLabel: "Adjust their theme",
  publishLabel: "Publish",
  publishHint: "Makes them visible to everyone on this conductor. Only their author can publish.",
  publishRefused: "Only their author can publish them.",
  systemLabel: "System prompt",
  systemHint: "Extra instructions, if you want them. Optional.",
  backLabel: "Close settings",
  sectionIdentity: "Identity",
  sectionMind: "Mind",
  sectionVoice: "Voice",
  pronounsLabel: "Pronouns",
  pronounsHint: "How the character is referred to. The model is told, and the app follows.",
  sectionMisc: "Misc",
  identityBlurb: "What they are called, and the first thing they say.",
  mindBlurb: "How they think, where you are, and what they will never do.",
  voiceBlurb: "How they sound when they send a voice note.",
  miscBlurb: "Who else can meet them, and everything without a home of its own.",
  darkLabel: "Dark mode",
  lightLabel: "Light mode",
  unsaved: "Unsaved changes",
  unsavedOne: "1 unsaved change",
  unsavedMany: "%d unsaved changes",
  discard: "Discard",
  ownerYou: "Yours",
  ownerTheirs: "Written by somebody else",
  theirsEditable:
    "Change anything you like. Saving keeps a private copy for you and leaves theirs as it is.",
  publishHintTheirs: "You can publish your own copy of them, once you have saved one.",
  ownerUnclaimed: "Unclaimed",
  forkWarning: "Your copy starts private. Publish it here when you want others to meet them.",
} as const;

export const MOOD_COPY = {
  title: "{{Their}} mood",
  hint: "Sets how {{they}} feel{{s}} going into the next reply. {{They}} may drift from it on {{their}} own.",
  close: "Close mood picker",
  holdLabel: "Hold this mood",
  holdHint:
    "Keeps {{them}} here until you turn this off. Otherwise it colours the next reply only.",
  clear: "Clear the mood",
  clearHeld: (mood: string) => `Stop holding "${mood}"`,
  clearOnce: (mood: string) => `Clear "${mood}" from the next reply`,
} as const;

export const CHAT_COPY = {
  nothingToRegenerate: "There is no reply to write again yet.",
  regenerate: "Write it again",
  anotherReply: "Say something else",
  pickReplacement: "Choose one to replace it",
  rerollOptions: "Reroll",
  dismissOptions: "Keep what she said",
  noSuggestions: "Nothing came back. Try the reroll.",
  loadingName: "Loading the name",
  speakMessage: "Read it aloud",
  nothingToSpeak: "There are no words in this one to read.",
  voiceUnconfigured: "No voice service is configured, so nothing can be read aloud.",
  voiceFailed: "The voice service did not answer. Try again.",
  respeakMessage: "Read it aloud again",
  holdToEditOption: "Tap to use it. Hold to change it first.",
  editMessage: "Edit this message",
  saveMessage: "Save",
  messageActions: "Message actions",
} as const;

export const CONFIRM_COPY = {
  keep: "Keep it",
  deleteCharacter: "Delete this character?",
  deleteCharacterBody:
    "Everything they said, the chapters, the lorebook and the gallery go with them. This cannot be undone.",
  deleteCharacterAction: "Delete them",
  resetChat: "Start this chat over?",
  resetChatBody:
    "Every message and every chapter is deleted, and how they feel about you goes back to the beginning. The character itself stays.",
  resetChatAction: "Start over",
  deleteAccount: "Remove this account?",
  deleteAccountBody: "They lose access to this conductor immediately. What they made stays.",
  deleteAccountAction: "Remove them",
  deleteMessage: "Delete this message?",
  deleteMessageBody: "Anything said after it will be answering something that is no longer there.",
  deletePhoto: "Delete this photo?",
  deletePhotoBody: "It is removed from the gallery and from storage.",
  resetPrompt: "Put this prompt back?",
  resetPromptBody: "Your version is discarded and the shipped wording returns.",
  resetPromptAction: "Put it back",
  resetSetting: "Put this setting back?",
  resetSettingBody: "The override is dropped and the shipped value returns.",
  resetTheme: "Put the whole theme back?",
  resetThemeBody: "Every colour, corner and typeface you changed returns to what shipped.",
  resetThemeAction: "Put it back",
  signOut: "Sign out of this conductor?",
  signOutBody: "This device forgets your session. Nothing on the conductor is deleted.",
  signOutAction: "Sign out",
  promoteTheme: "Make this the look for everyone?",
  promoteThemeBody: "This character's colours replace the shared ones.",
  promoteThemeAction: "Use everywhere",
  cancelProactive: "Cancel the message they were going to send?",
  cancelProactiveBody:
    "They will not write unprompted this time. The next reply you send schedules a new one.",
  cancelProactiveAction: "Cancel it",
  proactiveWaiting: (at: string) => `Waiting to write unprompted at ${at}`,
} as const;

export const DASHBOARD_COPY = {
  title: "Dashboard",
  blurb: "The levers behind the app, for whoever owns this conductor.",
  tile: "Dashboard",
  back: "Back",
  promptsTitle: "Prompts",
  promptsBlurb: "Every instruction the model is given, and what it shipped as.",
  charactersTitle: "Characters",
  charactersBlurb: "The whole roster, including what other accounts made.",
  usersTitle: "Accounts",
  usersBlurb: "Who can sign in, and which of them owns the place.",
  themeTitle: "Theme",
  themeBlurb: "The tokens the conductor serves, over the shipped palette.",
  configTitle: "Configuration",
  configBlurb: "Every setting, what can change and what cannot.",
  save: "Save",
  saving: "Saving…",
  saved: "Saved",
  reset: "Reset to default",
  resetAll: "Reset everything",
  remove: "Delete",
  cancel: "Cancel",
  edit: "Edit",
  add: "Add",
  create: "Create",
  loading: "Reading the conductor…",
  failed: "Could not reach the conductor.",
  empty: "Nothing here yet.",
  search: "Search",
  custom: "Changed",
  shipped: "As shipped",
  confirmRemove: "Delete this for good?",
  nameLabel: "Name",
  roleLabel: "Role",
  ownerBadge: "Owner",
  memberBadge: "Member",
  promote: "Make owner",
  demote: "Make member",
  you: "You",
  overriddenCount: (count: number) => `${count} changed from the default`,
  auditTitle: "Audit",
  auditBlurb: "Every change made from here, and who made it.",
  auditEmpty: "Nothing has been changed from the dashboard yet.",
  auditClear: "Clear the log",
  auditRetained: (kept: number, retain: number) => `${kept} kept, oldest dropped past ${retain}`,
  auditRefused: "Refused",
  auditBy: "by",
  auditAnonymous: "no account",
  storageTitle: "Storage",
  storageBlurb: "What the bucket holds, and what nothing points at any more.",
  storageScan: "Look for orphans",
  storageScanShort: "Scan",
  storageSweepShort: "Sweep",
  storageSweep: "Delete the orphans",
  storageScanning: "Reading the bucket…",
  storageOffline: "No bucket is connected.",
  storageNoReferences:
    "The bucket holds objects but the library named none, so a sweep is refused.",
  storageClean: "Nothing is unreferenced.",
  storageOrphans: (count: number) => `${count} unreferenced`,
  storageScanned: (scanned: number, referenced: number) =>
    `${scanned} in the bucket, ${referenced} still pointed at`,
  storageFreed: (count: number, mb: string) => `Deleted ${count} objects, freeing ${mb} MB`,
  storageBrowse: "In the bucket",
  storageAll: "All",
  storageOnlyOrphans: "Unreferenced",
  storageReferenced: "In use",
  storageImages: "Pictures",
  storageAudio: "Voice",
  storageOther: "Other",
  storageFlatMode: "One list",
  storageFolderMode: "By folder",
  storageMore: "Show more",
  storagePrevious: "Back",
  storageNext: "Next",
  storagePage: (page: number, pages: number) => `Page ${page} of ${pages}`,
  storageShowing: (shown: number, matched: number) => `${shown} of ${matched}`,
  storageFolders: (count: number) => (count === 1 ? "1 folder" : `${count} folders`),
  storageDeleteOne: "Delete this object?",
  storageDeleteOneBody: "It is removed from the bucket immediately. Nothing points at it.",
  copy: "Copy the link",
  copied: "Link copied",
  share: "Share or copy",
  sharing: "Getting it ready…",
  shareUnavailable: "This device cannot share files.",
  shareFailed: "Could not share that one.",
  download: "Save a copy",
  downloading: "Saving…",
  downloadedGallery: "Saved to your photos.",
  downloadedFile: (name: string) => `Saved ${name} to this app's files.`,
  downloadDenied: "Eidolon needs permission to save to your photos.",
  downloadFailed: "Could not save that one.",
  healthTitle: "Services",
  healthBlurb: "What the conductor can reach right now.",
  queuesTitle: "Queues",
  queuesBlurb:
    "Photos, portraits, backdrops and uploads, waiting their turn. Work here survives a closed app.",
  queuesEmpty: "Nothing queued.",
  queueRetry: "Try again",
  queueRemove: "Drop it",
  queueRetryAll: "Retry every failed job",
  queueEdit: "Edit the input",
  queueEditHint: "Only a failed job can be edited. Fields left alone keep their value.",
  queueSaveRetry: "Save and try again",
  queueSave: "Save",
  queueNotEditable: "Set when the job was made",
  queueStatePending: "Open",
  queueStateActive: "Running",
  queueStateWaiting: "Waiting",
  queueStateDelayed: "Later",
  queueStateFailed: "Failed",
  queueStateCompleted: "Done",
  summarizeNow: "Write a chapter now",
  summarizeQueued: "Queued. The chapter appears when the GPU is done.",
} as const;

export const AUTH_COPY = {
  signInRequired: "Sign in to reach this.",
  ownerOnly: "This needs the owner account.",
  noSuchAccount: "No such account.",
  lastOwner: "The last owner cannot be demoted or removed.",
  notYourself: "You cannot remove the account you are signed in as.",
  unknownRole: "Unknown role.",
  signUpTitle: "Make an account",
  signInTitle: "Sign in",
  emailLabel: "Email",
  passwordLabel: "Password",
  nameLabel: "Name",
  addressLabel: "Conductor address",
  signUpAction: "Create it",
  signInAction: "Sign in",
  signOutAction: "Sign out",
  tabSignIn: "Sign in",
  tabSignUp: "Create account",
  working: "One moment…",
  missingFields: "Fill in every field first.",
  failed: "That did not work. Check the address and try again.",
  firstAccountNote: "The first account on a conductor becomes its owner.",
  showPassword: "Show the password",
  hidePassword: "Hide the password",
  namePlaceholder: "What should we call you",
  emailPlaceholder: "you@example.com",
  passwordPlaceholder: "At least 8 characters",
  passwordTooShort: "That password is too short.",
  emailLooksWrong: "That does not look like an email address.",
} as const;

export const ADMIN_COPY = {
  title: "Admin controls",
  blurb: "Levers for working on a chat rather than living in one.",
  tile: "Admin",
  editAnyLabel: "Edit any message",
  editAnyHint:
    "Off, only her newest reply can be rewritten. Changing an older one leaves everything she said after it answering something that is no longer there.",
  speakAnyLabel: "Read any message aloud",
  speakAnyHint: "Shows the speaker on every one of her replies, not just the newest.",
  momentBackgroundLabel: "Let moments paint the background",
  momentBackgroundHint:
    "On by default, so a moment paints the place behind this chat. Setting a background by hand turns it off and keeps yours. Turn it back on to hand the background to moments again.",
} as const;

export const CHARACTER_TASTE_COPY = {
  likesLabel: "Likes",
  likesHint: "What they are drawn to. A short list, not a sentence.",
  dislikesLabel: "Dislikes",
  dislikesHint: "What puts them off. A short list, not a sentence.",
} as const;

export const QUEUE_COPY = {
  onlyOne: "On the GPU now",
  nextUp: "Next on the GPU",
  waiting: "Waiting on the GPU",
  place: "%p of %t",
  announceChatPhotosLabel: "Announce where photos are queued",
  announceChatPhotosHint:
    "Portraits always say where they are in the queue. Turn this on to hear the same for photos asked for in a chat.",
  announceFailed: "Only the owner of this conductor can change that.",
} as const;

export const PERSONA_COPY = {
  title: "Who you are",
  blurb: "What a character knows about you when you talk to them.",
  tile: "Your personas",
  empty: "No personas yet. The first one you write is the one every character will read.",
  create: "New persona",
  createTitle: "A new persona",
  rename: "Rename",
  remove: "Delete",
  removeBody: "Nothing you have said is lost, but characters stop reading this version of you.",
  removeAction: "Delete it",
  makeDefault: "Use everywhere",
  isDefault: "Used everywhere",
  defaultHint: "Every character reads this one unless you pin them to another.",
  pinned: "Pinned to this chat",
  usesDefault: "Reads whoever is used everywhere",
  photoLabel: "Your picture",
  photoHint: "Shown beside your name. Not used to draw you, yet.",
  photoChange: "Change picture",
  photoGenerate: "Draw me",
  photoOpen: "Open your picture",
  photoClose: "Close",
  photoEmpty: "No picture yet. Draw one from what you have written, or choose one from your phone.",
  photoGenerateHint: "Draw a picture from what you have written about yourself.",
  photoQueued: "Drawing you. It takes a minute.",
  photoFailed: "The portrait could not be drawn.",
  photoNeedsSomething: "Write a bio or a personality first, so there is something to draw from.",
  photoRemove: "Remove picture",
  namePlaceholder: "What they should call you",
  bioPlaceholder: "Who you are, in a few lines",
  hobbiesPlaceholder: "What you do with your own time",
  likesPlaceholder: "What you are drawn to",
  dislikesPlaceholder: "What puts you off",
  personalityPlaceholder: "How you are to talk to",
  chaptersTitle: "Chapters of your life",
  chaptersBlurb: "What happened to you, in the order it happened.",
  chapterAdd: "Add a chapter",
  chapterTitlePlaceholder: "What to call this stretch",
  chapterBodyPlaceholder: "Where you were, what you were doing, what changed",
  chapterEmpty: "No chapters yet. Add the first one and characters can refer back to it.",
  chapterRemove: "Delete chapter",
  chapterRemoveBody: "The chapter goes, and characters stop reading it.",
  saved: "Saved",
  needName: "Give the persona a name first.",
  unnamed: "Unnamed persona",
  characterLikes: "Likes",
  characterDislikes: "Dislikes",
  characterLikesPlaceholder: "What they are drawn to",
  characterDislikesPlaceholder: "What puts them off",
} as const;
