export const IMAGE = {
  checkpoint: "RealVisXL_V5.0_Lightning_fp16.safetensors",
  pulidModel: "ip-adapter_pulid_sdxl_fp16.safetensors",
  insightFaceProvider: "CUDA",
  widthPx: 832,
  heightPx: 1216,
  landscapeWidthPx: 1216,
  landscapeHeightPx: 832,
  squarePx: 1024,
  sceneTurns: 6,
  lookFieldMaxWords: 4,
  // The scene planner is told twelve words a field and does not obey it, so the
  // cap is applied here instead. Without it "others" arrived as a whole clause
  // and was pasted straight into a caption: "with Her cat, Luna, is curled up
  // on the bed at Emma's bedroom, Emma is".
  sceneFieldMaxWords: 8,
  // "others" is meant to name who else is in frame. A clause is a description of
  // the room, not a person, and reads as nonsense after the word "with".
  othersClauseWords: ["is", "are", "was", "were", "hanging", "sitting on", "lying on"],
  emptyWords: [
    "none",
    "nothing",
    "n/a",
    "na",
    "empty",
    "no one",
    "no-one",
    "nobody",
    "null",
    "undefined",
    "just me",
    "just her",
    "only her",
    "herself",
    "alone",
    "-",
  ],
  hairChangeWords: [
    "dyed",
    "dye",
    "bleached",
    "highlights",
    "bangs",
    "fringe",
    "buzzcut",
    "shaved",
    "braids",
    "haircut",
    "extensions",
  ],
  hairColourWords: [
    "red",
    "blonde",
    "blond",
    "brunette",
    "black",
    "brown",
    "pink",
    "blue",
    "green",
    "purple",
    "silver",
    "white",
    "ginger",
    "auburn",
    "platinum",
  ],
  bodyChangeWords: ["tan", "tanned", "sunburnt", "wet", "freckled", "glasses", "makeup"],
  ideaCount: 4,
  ideaMaxChars: 60,
  ideaMaxWords: 9,
  ideaOverlap: 0.6,
  ideaTemperature: 0.95,
  editDenoise: 0.62,
  steps: 6,
  cfg: 2,
  sampler: "dpmpp_sde",
  scheduler: "karras",
  pulidMethod: "fidelity",
  pulidWeight: 0.75,
  pulidStartAt: 0.12,
  pulidEndAt: 1,
  framings: [
    "close selfie held at arm's length, looking into the lens",
    "selfie held high, looking up at the camera",
    "mirror selfie, phone visible in the reflection",
    "waist up, taken by someone else, not looking at the camera",
    "full length shot from a few steps away",
    "candid photo caught mid laugh, looking off to the side",
    "over the shoulder, glancing back at the camera",
    "three quarter view, head turned away from the lens",
    "sitting down, leaning on one hand, looking past the camera",
    "wide shot with her small in the frame and the place around her",
    "low angle from below, looking down at the lens",
    "cropped close on her face, half in shadow",
  ],
  flourishes: [
    "sunglasses pushed up into her hair",
    "wearing sunglasses",
    "hair tied up messily",
    "holding a drink",
    "one hand pushing her hair back",
    "mid sentence, mouth slightly open",
    "squinting into the sun",
    "wrapped in a coat against the cold",
    "peace sign, not taking it seriously",
    "looking down at something out of frame",
    "",
    "",
  ],
  wideWords: [
    "view",
    "views",
    "landscape",
    "scenery",
    "scenic",
    "sunset",
    "sunrise",
    "beach",
    "mountain",
    "mountains",
    "hike",
    "hiking",
    "skyline",
    "city",
    "street",
    "field",
    "lake",
    "river",
    "sea",
    "ocean",
    "valley",
    "forest",
    "road",
    "trip",
    "travel",
    "panorama",
    "horizon",
    "garden",
    "park",
  ],
  qualitySuffix: "photorealistic, natural skin texture, sharp focus, shot on a phone camera",
  negativePrompt:
    "blurry, low quality, distorted, bad anatomy, extra fingers, watermark, text, cgi, plastic skin",
  appearanceFallback:
    "a woman in her late twenties, shoulder length dark hair, warm brown eyes, casual everyday clothes",
  captionMaxChars: 90,
  captionAttempts: 3,
  captionMinWords: 3,
  captionMaxWords: 14,
  captionMaxTokens: 72,
  captionTemperature: 1.0,
  captionPresencePenalty: 0.8,
  captionFrequencyPenalty: 0.6,
  promptMaxTokens: 480,
  promptMaxChars: 2000,
  appearanceTemperature: 0.4,
  sceneTemperature: 0.7,
  pollIntervalMs: 750,
  maxPollMs: 180000,
} as const;
