import {
  AFFINITY as SHIPPED_AFFINITY,
  AUDIT as SHIPPED_AUDIT,
  AUTHOR_FIELDS as SHIPPED_AUTHOR_FIELDS,
  AUTHORING as SHIPPED_AUTHORING,
  CACHE as SHIPPED_CACHE,
  CARD_UPLOAD as SHIPPED_CARD_UPLOAD,
  CHAT_TURN as SHIPPED_CHAT_TURN,
  CHRONICLE as SHIPPED_CHRONICLE,
  CHRONICLE_CONTEXT as SHIPPED_CHRONICLE_CONTEXT,
  ENHANCE as SHIPPED_ENHANCE,
  IMAGE as SHIPPED_IMAGE,
  IMAGE_ENCODE as SHIPPED_IMAGE_ENCODE,
  KOKORO as SHIPPED_KOKORO,
  LOREBOOK as SHIPPED_LOREBOOK,
  MEMORY as SHIPPED_MEMORY,
  MIND_UPDATE as SHIPPED_MIND_UPDATE,
  PERSONA_GUARD as SHIPPED_PERSONA_GUARD,
  PORTRAIT as SHIPPED_PORTRAIT,
  PROACTIVE as SHIPPED_PROACTIVE,
  PROMPT_AUTHORING as SHIPPED_PROMPT_AUTHORING,
  PROMPT_BUDGET as SHIPPED_PROMPT_BUDGET,
  QUEUE_ANNOUNCE as SHIPPED_QUEUE_ANNOUNCE,
  QUEUE_VIEW as SHIPPED_QUEUE_VIEW,
  RECALL as SHIPPED_RECALL,
  REPLY_VARIANTS as SHIPPED_REPLY_VARIANTS,
  SEARCH as SHIPPED_SEARCH,
  SENTENCE_BUFFER as SHIPPED_SENTENCE_BUFFER,
  STAGE as SHIPPED_STAGE,
  STAGE_DIRECTIONS as SHIPPED_STAGE_DIRECTIONS,
  STORAGE_BROWSER as SHIPPED_STORAGE_BROWSER,
  STORAGE_SWEEP as SHIPPED_STORAGE_SWEEP,
  SUGGESTIONS as SHIPPED_SUGGESTIONS,
  TIMEOUTS_MS as SHIPPED_TIMEOUTS_MS,
  TRANSCRIBE as SHIPPED_TRANSCRIBE,
  TRANSCRIPT as SHIPPED_TRANSCRIPT,
  TTS as SHIPPED_TTS,
  VOICE as SHIPPED_VOICE,
  WEB_CONTEXT as SHIPPED_WEB_CONTEXT,
  WORKING_CONTEXT as SHIPPED_WORKING_CONTEXT,
} from "@eidolon/config";
import { resolvedGroup } from "@/services/config-overlay";

export const AFFINITY = resolvedGroup("AFFINITY", SHIPPED_AFFINITY);
export const AUDIT = resolvedGroup("AUDIT", SHIPPED_AUDIT);
export const AUTHORING = resolvedGroup("AUTHORING", SHIPPED_AUTHORING);
export const AUTHOR_FIELDS = resolvedGroup("AUTHOR_FIELDS", SHIPPED_AUTHOR_FIELDS);
export const CACHE = resolvedGroup("CACHE", SHIPPED_CACHE);
export const CARD_UPLOAD = resolvedGroup("CARD_UPLOAD", SHIPPED_CARD_UPLOAD);
export const CHAT_TURN = resolvedGroup("CHAT_TURN", SHIPPED_CHAT_TURN);
export const CHRONICLE = resolvedGroup("CHRONICLE", SHIPPED_CHRONICLE);
export const CHRONICLE_CONTEXT = resolvedGroup("CHRONICLE_CONTEXT", SHIPPED_CHRONICLE_CONTEXT);
export const ENHANCE = resolvedGroup("ENHANCE", SHIPPED_ENHANCE);
export const IMAGE = resolvedGroup("IMAGE", SHIPPED_IMAGE);
export const IMAGE_ENCODE = resolvedGroup("IMAGE_ENCODE", SHIPPED_IMAGE_ENCODE);
export const KOKORO = resolvedGroup("KOKORO", SHIPPED_KOKORO);
export const LOREBOOK = resolvedGroup("LOREBOOK", SHIPPED_LOREBOOK);
export const MEMORY = resolvedGroup("MEMORY", SHIPPED_MEMORY);
export const MIND_UPDATE = resolvedGroup("MIND_UPDATE", SHIPPED_MIND_UPDATE);
export const PERSONA_GUARD = resolvedGroup("PERSONA_GUARD", SHIPPED_PERSONA_GUARD);
export const PORTRAIT = resolvedGroup("PORTRAIT", SHIPPED_PORTRAIT);
export const QUEUE_ANNOUNCE = resolvedGroup("QUEUE_ANNOUNCE", SHIPPED_QUEUE_ANNOUNCE);
export const PROACTIVE = resolvedGroup("PROACTIVE", SHIPPED_PROACTIVE);
export const PROMPT_AUTHORING = resolvedGroup("PROMPT_AUTHORING", SHIPPED_PROMPT_AUTHORING);
export const PROMPT_BUDGET = resolvedGroup("PROMPT_BUDGET", SHIPPED_PROMPT_BUDGET);
export const QUEUE_VIEW = resolvedGroup("QUEUE_VIEW", SHIPPED_QUEUE_VIEW);
export const RECALL = resolvedGroup("RECALL", SHIPPED_RECALL);
export const REPLY_VARIANTS = resolvedGroup("REPLY_VARIANTS", SHIPPED_REPLY_VARIANTS);
export const SEARCH = resolvedGroup("SEARCH", SHIPPED_SEARCH);
export const SENTENCE_BUFFER = resolvedGroup("SENTENCE_BUFFER", SHIPPED_SENTENCE_BUFFER);
export const STAGE = resolvedGroup("STAGE", SHIPPED_STAGE);
export const STAGE_DIRECTIONS = resolvedGroup("STAGE_DIRECTIONS", SHIPPED_STAGE_DIRECTIONS);
export const STORAGE_BROWSER = resolvedGroup("STORAGE_BROWSER", SHIPPED_STORAGE_BROWSER);
export const STORAGE_SWEEP = resolvedGroup("STORAGE_SWEEP", SHIPPED_STORAGE_SWEEP);
export const SUGGESTIONS = resolvedGroup("SUGGESTIONS", SHIPPED_SUGGESTIONS);
export const TIMEOUTS_MS = resolvedGroup("TIMEOUTS_MS", SHIPPED_TIMEOUTS_MS);
export const TRANSCRIBE = resolvedGroup("TRANSCRIBE", SHIPPED_TRANSCRIBE);
export const TRANSCRIPT = resolvedGroup("TRANSCRIPT", SHIPPED_TRANSCRIPT);
export const TTS = resolvedGroup("TTS", SHIPPED_TTS);
export const VOICE = resolvedGroup("VOICE", SHIPPED_VOICE);
export const WEB_CONTEXT = resolvedGroup("WEB_CONTEXT", SHIPPED_WEB_CONTEXT);
export const WORKING_CONTEXT = resolvedGroup("WORKING_CONTEXT", SHIPPED_WORKING_CONTEXT);
